# Generated by Django 4.1.5 on 2023-04-07 11:29

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_choice', models.CharField(choices=[('TA', 'Танки'), ('SI', 'Хиллы'), ('DD', 'ДД'), ('TR', 'Торговцы'), ('GU', 'Гилдмастеры'), ('QU', 'Квестгиверы'), ('BL', 'Кузнецы'), ('SK', 'Кожевники'), ('PO', 'Зельевары'), ('MA', 'Мастера заклинаний')], default='TA', max_length=2)),
                ('title', models.CharField(max_length=128)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('time_creation', models.DateField(auto_now_add=True)),
                ('upload', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_add', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='callboard.post')),
            ],
        ),
    ]
