# Generated by Django 4.1.5 on 2023-05-14 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
